/* ::: FUN FACTS ::: */
var weeklyFacts = [
//Week 1 	value 0
"You're not pregnant yet, but you may be about to release an egg that could grow into a baby if it's fertilized by your partner's sperm. Last week an increase in the amount of estrogen and progesterone coursing through your bloodstream prompted your uterus to form a lush, blood-rich lining of tissue to support a potential fertilized egg. At the same time, in your ovaries, eggs were ripening in fluid-filled sacs called follicles. At the beginning of this week (often around day 14 of a 28-day cycle), you ovulate: One of your eggs erupts from its follicle and is swept away from your ovary and into a fallopian tube. During the next 12 to 24 hours, that egg will be fertilized if one of the 250 million sperm (on average) ejaculated by your mate manages to swim all the way from your vagina through your cervix, up through your uterus to the fallopian tube, and penetrate the egg. Only about 400 sperm will survive the arduous 10-hour journey to the egg, and only one can succeed in burrowing through its outer membrane. Over the next 10 to 30 hours, the sperm's nucleus will merge with the egg's as they combine their genetic material. If the sperm carries a Y chromosome, your baby will be a boy. If it's an X chromosome, you'll be carrying a girl. During the three- to four-day trip from your fallopian tube to your uterus, the fertilized egg (now called a zygote) will divide into 16 identical cells. Once it enters the uterus, the zygote is called a morula. A day or two later, it will begin burrowing into the lush lining of your uterus, continuing its amazing growth and transformation. By this time, your developing baby is a little ball of cells that's officially referred to by scientists as a blastocyst: It has an inner cell mass that will become the embryo itself, a fluid-filled cavity that will become the amniotic sac, and an outer cell mass that will become the placenta, the pancake-shaped organ that delivers life-sustaining oxygen and nutrients to your baby and carries away waste products.",
//Week 2 	value 1  
"You're not pregnant yet, but you may be about to release an egg that could grow into a baby if it's fertilized by your partner's sperm. Last week an increase in the amount of estrogen and progesterone coursing through your bloodstream prompted your uterus to form a lush, blood-rich lining of tissue to support a potential fertilized egg. At the same time, in your ovaries, eggs were ripening in fluid-filled sacs called follicles. At the beginning of this week (often around day 14 of a 28-day cycle), you ovulate: One of your eggs erupts from its follicle and is swept away from your ovary and into a fallopian tube. During the next 12 to 24 hours, that egg will be fertilized if one of the 250 million sperm (on average) ejaculated by your mate manages to swim all the way from your vagina through your cervix, up through your uterus to the fallopian tube, and penetrate the egg. Only about 400 sperm will survive the arduous 10-hour journey to the egg, and only one can succeed in burrowing through its outer membrane. Over the next 10 to 30 hours, the sperm's nucleus will merge with the egg's as they combine their genetic material. If the sperm carries a Y chromosome, your baby will be a boy. If it's an X chromosome, you'll be carrying a girl. During the three- to four-day trip from your fallopian tube to your uterus, the fertilized egg (now called a zygote) will divide into 16 identical cells. Once it enters the uterus, the zygote is called a morula. A day or two later, it will begin burrowing into the lush lining of your uterus, continuing its amazing growth and transformation. By this time, your developing baby is a little ball of cells that's officially referred to by scientists as a blastocyst: It has an inner cell mass that will become the embryo itself, a fluid-filled cavity that will become the amniotic sac, and an outer cell mass that will become the placenta, the pancake-shaped organ that delivers life-sustaining oxygen and nutrients to your baby and carries away waste products.",
//Week 3 	value 2
"A momentous meeting has taken place inside you – a single sperm has broken through the tough outer membrane of your egg and fertilized it. Several days later, the fertilized egg arrived in the uterus and started burrowing into the lining. A baby is in the making! Your little one is just a tiny ball (called a blastocyst), consisting of several hundred cells that are multiplying madly. The part of it that will develop into the placenta has started producing the pregnancy hormone hCG (human chorionic gonadotropin), which tells your ovaries to stop releasing eggs and triggers increased production of estrogen and progesterone. These hormones keep your uterus from shedding its lining – and its tiny passenger – and stimulate the growth of the placenta. Meanwhile, amniotic fluid is beginning to collect around the ball of cells in the cavity that will become the amniotic sac. This fluid will cushion your baby in the weeks and months ahead. Right now, your little blastocyst is receiving oxygen and nutrients (and discarding waste) through a primitive circulation system made up of microscopic tunnels that connect your developing baby to the blood vessels in your uterine wall. The placenta won't be developed enough to take over this task until the end of next week.",
//Week 4 	value 3
"This week marks the beginning of the embryonic period. From now until 10 weeks, all of your baby's organs will begin to develop and some will even begin to function. As a result, this is the time when she'll be most vulnerable to anything that might interfere with her development. Right now your baby is an embryo the size of a poppy seed, consisting of two layers: the epiblast and the hypoblast, from which all of her organs and body parts will develop. The primitive placenta is also made up of two layers at this point. Its cells are tunneling into the lining of your uterus, creating spaces for your blood to flow so that the developed placenta will be able to provide nutrients and oxygen to your growing baby when it starts to function at the end of this week. Also present now are the amniotic sac, which will house your baby; the amniotic fluid, which will cushion her as she grows; and the yolk sac, which produces your baby's red blood cells and helps deliver nutrients to her until the placenta has developed and is ready to take over this duty.",
//Week 5 	value 4
"Deep in your uterus your embryo is growing at a furious pace. At this point, he's about the size of a sesame seed, and he looks more like a tiny tadpole than a human. He's now made up of three layers — the ectoderm, the mesoderm, and the endoderm — which will later form all of his organs and tissues. The neural tube — from which your baby's brain, spinal cord, nerves, and backbone will sprout — is starting to develop in the top layer, called the ectoderm. This layer will also give rise to his skin, hair, nails, mammary and sweat glands, and tooth enamel. His heart and circulatory system begin to form in the middle layer, or mesoderm. (This week, in fact, his tiny heart begins to divide into chambers and beat and pump blood.) The mesoderm will also form your baby's muscles, cartilage, bone, and subcutaneous (under skin) tissue. The third layer, or endoderm, will house his lungs, intestines, and rudimentary urinary system, as well as his thyroid, liver, and pancreas. In the meantime, the primitive placenta and umbilical cord, which deliver nourishment and oxygen to your baby, are already on the job.",
//Week 6 	value 5
"This week's major developments: The nose, mouth, and ears that you'll spend so much time kissing in eight months are beginning to take shape. If you could see into your uterus, you'd find an oversize head and dark spots where your baby's eyes and nostrils are starting to form. His emerging ears are marked by small depressions on the sides of the head, and his arms and legs by protruding buds. His heart is beating about 100 to 160 times a minute — almost twice as fast as yours — and blood is beginning to course through his body. His intestines are developing, and the bud of tissue that will give rise to his lungs has appeared. His pituitary gland is forming, as are the rest of his brain, muscles, and bones. Right now, your baby is a quarter of an inch long, about the size of a lentil.",
//Week 7 	value 6
"The big news this week: Your baby’s hands and feet are emerging from developing arms and legs — although they look more like paddles at this point than the tiny baby fingers and toes you're daydreaming about holding and tickling. Technically, your baby is still considered an embryo and has something of a small tail, which is an extension of her tailbone. The tail will disappear within a few weeks, but that's the only thing getting smaller. Your baby has doubled in size since last week and now measures half an inch long, about the size of a blueberry. If you could see inside your womb, you'd spot eyelid folds partially covering her peepers, which already have some color, as well as the tip of her nose and tiny veins beneath parchment-thin skin. Both hemispheres of your baby's brain are growing, and her liver is churning out red blood cells until her bone marrow forms and takes over this role. She also has an appendix and a pancreas, which will eventually produce the hormone insulin to aid in digestion. A loop in your baby's growing intestines is bulging into her umbilical cord, which now has distinct blood vessels to carry oxygen and nutrients to and from her tiny body.",
//Week 8 	value 7
"New this week: Your baby's hands and feet are developing webbed fingers and toes, his eyelids almost cover his eyes, breathing tubes extend from his throat to the branches of his developing lungs, and his 'tail' is just about gone. In his brain, nerve cells are branching out to connect with one another, forming primitive neural pathways. You may be daydreaming about having a boy or a girl, but the external genitals still haven't developed enough to reveal your baby’s sex. (Try our Chinese gender predictor for an early guess!) Either way, your baby — about the size of a kidney bean — is constantly moving and shifting, though you still can't feel it.",
//Week 9 	value 8
"Your new resident is nearly an inch long — about the size of a grape — and weighs just a fraction of an ounce. She's starting to look more and more human. Her essential body parts are accounted for, though they'll go through plenty of fine-tuning in the coming months. Other changes abound: Your baby's heart finishes dividing into four chambers, and the valves start to form — as do her tiny teeth. The embryonic 'tail' is completely gone. Your baby's organs, muscles, and nerves are kicking into gear. The external sex organs are there but won't be distinguishable as male or female for another few weeks. Her eyes are fully formed, but her eyelids are fused shut and won't open until 27 weeks. She has tiny earlobes, and her mouth, nose, and nostrils are more distinct. The placenta is developed enough now to take over most of the critical job of producing hormones. Now that your baby's basic physiology is in place, she's poised for rapid weight gain.",
//Week 10 	value 9
"Though he's barely the size of a kumquat — a little over an inch or so long, crown to bottom — and weighs less than a quarter of an ounce, your baby has now completed the most critical portion of his development. This is the beginning of the so-called fetal period, a time when the tissues and organs in his body rapidly grow and mature. He's swallowing fluid and kicking up a storm. Vital organs — including his kidneys, intestines, brain, and liver (now making red blood cells in place of the disappearing yolk sac) — are in place and starting to function, though they'll continue to develop throughout your pregnancy. If you could take a peek inside your womb, you'd spot minute details, like tiny nails forming on fingers and toes (no more webbing) and peach-fuzz hair beginning to grow on tender skin. In other developments: Your baby's limbs can bend now. His hands are flexed at the wrist and meet over his heart, and his feet may be long enough to meet in front of his body. The outline of his spine is clearly visible through translucent skin, and spinal nerves are beginning to stretch out from his spinal cord. Your baby's forehead temporarily bulges with his developing brain and sits very high on his head, which measures half the length of his body. From crown to rump, he's about 1 1/4 inches long. In the coming weeks, your baby will again double in size — to nearly 3 inches.",
//Week 11 	value 10
"Your baby, just over 1 1/2 inches long and about the size of a fig, is now almost fully formed. Her hands will soon open and close into fists, tiny tooth buds are beginning to appear under her gums, and some of her bones are beginning to harden. She's already busy kicking and stretching, and her tiny movements are so effortless they look like water ballet. These movements will become more frequent as her body grows and becomes more developed and functional. You won't feel your baby's acrobatics for another month or two — nor will you notice the hiccupping that may be happening now that her diaphragm is forming.",
//Week 12 	value 11  
"The most dramatic development this week: reflexes. Your baby's fingers will soon begin to open and close, his toes will curl, his eye muscles will clench, and his mouth will make sucking movements. In fact, if you prod your abdomen, your baby will squirm in response, although you won't be able to feel it. His intestines, which have grown so fast that they protrude into the umbilical cord, will start to move into his abdominal cavity about now, and his kidneys will begin excreting urine into his bladder. Meanwhile, nerve cells are multiplying rapidly, and in your baby's brain, synapses are forming furiously. His face looks unquestionably human: His eyes have moved from the sides to the front of his head, and his ears are right where they should be. From crown to rump, your baby-to-be is just over 2 inches long (about the size of a lime) and weighs half an ounce.",
//Week 13 	value 12
"Your baby's tiny fingertips have fingerprints, her veins and organs are clearly visible through her still-thin skin, and her body is starting to catch up with her head — which makes up just a third of her body size now. If you're having a girl, she now has more than 2 million eggs in her ovaries. Your baby is almost 3 inches long about the size of a (pea pod) and weighs nearly an ounce.",
//Week 14 	value 13
"This week's big developments: Your baby can now squint, frown, grimace, pee, and possibly suck his thumb! Thanks to brain impulses, his facial muscles are getting a workout as his tiny features form one expression after another. His kidneys are producing urine, which he releases into the amniotic fluid around him — a process he'll keep up until birth. He can grasp, too, and if you're having an ultrasound now, you may even catch him sucking his thumb. In other news: Your baby's stretching out. From head to bottom, he measures 3 1/2 inches — about the size of a lemon — and he weighs 1 1/2 ounces. His body's growing faster than his head, which now sits upon a more distinct neck. By the end of this week, his arms will have grown to a length that's in proportion to the rest of his body. (His legs still have some lengthening to do.) He's starting to develop an ultra-fine, downy covering of hair, called lanugo, all over his body. Your baby's liver starts making bile this week — a sign that it's doing its job right — and his spleen starts helping in the production of red blood cells. Though you can't feel his tiny punches and kicks yet, your little pugilist's hands and feet (which now measure about 1/2 inch long) are more flexible and active.",
//Week 15 	value 14
"Your growing baby now measures about 4 inches long, crown to rump, and weighs in at about 2 1/2 ounces (about the size of an apple). She's busy moving amniotic fluid through her nose and upper respiratory tract, which helps the primitive air sacs in her lungs begin to develop. Her legs are growing longer than her arms now, and she can move all of her joints and limbs. Although her eyelids are still fused shut, she can sense light. If you shine a flashlight at your tummy, for instance, she's likely to move away from the beam. There's not much for your baby to taste at this point, but she is forming taste buds. Finally, if you have an ultrasound this week, you may be able to find out whether your baby's a boy or a girl! (Don't be too disappointed if it remains a mystery, though. Nailing down your baby's sex depends on the clarity of the picture and on your baby's position. He or she may be modestly curled up or turned in such a way as to 'hide the goods.')",
//Week 16 	value 15
"Get ready for a growth spurt. In the next few weeks, your baby will double his weight and add inches to his length. Right now, he's about the size of an avocado: 4 1/2 inches long (head to rump) and 3 1/2 ounces. His legs are much more developed, his head is more erect than it has been, and his eyes have moved closer to the front of his head. His ears are close to their final position, too. The patterning of his scalp has begun, though his locks aren't recognizable yet. He's even started growing toenails. And there's a lot happening inside as well. For example, his heart is now pumping about 25 quarts of blood each day, and this amount will continue to increase as your baby continues to develop.",
//Week 17 	value 16
"Your baby's skeleton is changing from soft cartilage to bone, and the umbilical cord — her lifeline to the placenta — is growing stronger and thicker. Your baby weighs 5 ounces now (about as much as a turnip), and she's around 5 inches long from head to bottom. She can move her joints, and her sweat glands are starting to develop.",
//Week 18 	value 17
"Head to rump, your baby is about 5 1/2 inches long, and he weighs almost 7 ounces about the size of a (bell pepper). He's busy flexing his arms and legs — movements that you'll start noticing more and more in the weeks ahead. His blood vessels are visible through his thin skin, and his ears are now in their final position, although they're still standing out from his head a bit. A protective covering of myelin is beginning to form around his nerves, a process that will continue for a year after he's born. If you're having a girl, her uterus and fallopian tubes are formed and in place. If you're having a boy, his genitals are noticeable now, but he may hide them from you during an ultrasound.",
//Week 19 	value 18
"Your baby's sensory development is exploding! Her brain is designating specialized areas for smell, taste, hearing, vision, and touch. Some research suggests that she may be able to hear your voice now, so don't be shy about reading aloud, talking to her, or singing a happy tune if the mood strikes you. As for size, your baby weighs about 8 1/2 ounces and measures 6 inches, head to bottom — about the size of an heirloom tomato. Her arms and legs are in the right proportions to each other and the rest of her body now. Your baby's kidneys continue to make urine and the hair on her scalp is sprouting. A waxy protective coating called the vernix caseosa is forming on her skin to prevent it from pickling in the amniotic fluid.",
//Week 20 	value 19
"Your baby weighs about 10 1/2 ounces now. He's also around 6 1/2 inches long from head to bottom and about 10 inches from head to heel — about the size of a banana. (For the first 20 weeks, when a baby's legs are curled up against his torso and hard to measure, measurements are taken from the top of his head to his bottom — the 'crown to rump' measurement. After 20 weeks, he's measured from head to toe.)  He's swallowing more these days, which is good practice for his digestive system. He's also producing meconium, a black, sticky by-product of digestion. This gooey substance will accumulate in his bowels, and you'll see it in his first soiled diaper (some babies pass meconium in the womb or during delivery).",
//Week 21 	value 20
"Your baby now weighs about three-quarters of a pound and is approximately 10 1/2 inches long — about the size of a carrot. You may soon feel like he's practicing martial arts as his initial fluttering movements turn into full-fledged kicks and nudges. You may also discover a pattern to his activity as you get to know him better. In other developments, your baby's eyebrows and lids are present now.",
//Week 22 	value 21  
"At 11 inches and almost 1 pound (about the size of a spaghetti squash), your baby is starting to look like a miniature newborn. His lips, eyelids, and eyebrows are becoming more distinct, and he's even developing tiny tooth buds beneath his gums. His eyes have formed, but his irises (the colored part of the eye) still lack pigment. If you could see inside your womb, you'd be able to spot the fine hair (lanugo) that covers his body and the deep wrinkles on his skin, which he'll sport until he adds a padding of fat to fill them in. Inside his belly, his pancreas — essential for the production of some important hormones — is developing steadily.",
//Week 23 	value 22
"Turn on the radio and sway to the music. With his sense of movement well developed by now, your baby can feel you dance. And now that he's more than 11 inches long and weighs just over a pound (about the size of a large mango), you may be able to see him squirm underneath your clothes. Blood vessels in his lungs are developing to prepare for breathing, and the sounds that your baby's increasingly keen ears pick up are preparing him for entry into the outside world. Loud noises that become familiar now — such as your dog barking or the roar of the vacuum cleaner — probably won't faze him when he hears them outside the womb.",
//Week 24 	value 23
"Your baby's growing steadily, having gained about 4 ounces since last week. That puts him at about 1 1/3 pounds. Since he's almost a foot long (about the size of an ear of corn), he cuts a pretty lean figure at this point, but his body is filling out proportionally and he'll soon start to plump up. His brain is also growing quickly now, and his taste buds are continuing to develop. His lungs are developing 'branches' of the respiratory 'tree' as well as cells that produce surfactant, a substance that will help his air sacs inflate once he hits the outside world. His skin is still thin and translucent, but that will start to change soon.",
//Week 25 	value 24
"Head to heels, your baby now measures about 13 1/2 inches. His weight — 1 1/2 pounds — isn't much more than an average rutabaga, but he's beginning to exchange his long, lean look for some baby fat. As he does, his wrinkled skin will begin to smooth out and he'll start to look more and more like a newborn. He's also growing more hair — and if you could see it, you'd now be able to discern its color and texture.",
//Week 26 	value 25
"The network of nerves in your baby's ears is better developed and more sensitive than before. He may now be able to hear both your voice and your partner's as you chat with each other. He's inhaling and exhaling small amounts of amniotic fluid, which is essential for the development of his lungs. These so-called breathing movements are also good practice for when he's born and takes that first gulp of air. Your baby is continuing to put on baby fat. He now weighs about 1 2/3 pounds and measures 14 inches (about the size of a scallion) from head to heel. If you're having a boy, his testicles should soon begin to descend into his scrotum — a trip that will take about two to three months.",
//Week 27 	value 26
"This week, your baby weighs almost 2 pounds (about the size of a head of cauliflower) and is about 14 1/2 inches long with his legs extended. He's sleeping and waking at regular intervals, opening and closing his eyes, and perhaps even sucking his fingers. With more brain tissue developing, your baby's brain is very active now. While his lungs are still immature, they would be capable of functioning — with a lot of medical help — if he were to be born now. Chalk up any tiny rhythmic movements you may be feeling to a case of baby hiccups, which may be common from now on. Each episode usually lasts only a few moments, and they don't bother him, so just relax and enjoy the tickle.",
//Week 28 	value 27
"By this week, your baby weighs 2 1/4 pounds (about the size of a large eggplant) and measures 14.8 inches from the top of his head to his heels.  He can blink his eyes, which now sport lashes. With his eyesight developing, he may be able to see the light that filters in through your womb. He's also developing billions of neurons in his brain and adding more body fat in preparation for life in the outside world.",
//Week 29 	value 28
"Your baby now weighs about 2 1/2 pounds (about the size of a butternut squash) and is a tad over 15 inches long from head to heel. His muscles and lungs are continuing to mature, and his head is growing bigger to make room for his developing brain. To meet his increasing nutritional demands, you'll need plenty of protein, vitamins C, folic acid, and iron. And because his bones are soaking up lots of calcium, be sure to drink your milk (or find another good source of calcium, such as cheese, yogurt, or enriched orange juice). This trimester, about 250 milligrams of calcium are deposited in your baby's hardening skeleton each day.",
//Week 30 	value 29
"Your baby's about 15.7 inches long now and weighs almost 3 pounds (about the size of a large cabbage). A pint and a half of amniotic fluid surrounds her, but that volume will shrink as she gets bigger and takes up more room in your uterus. Her eyesight continues to develop, though it's not very keen; even after she's born, she'll keep her eyes closed for a good part of the day. When she does open them, she'll respond to changes in light but will have 20/400 vision — which means she can only make out objects a few inches from her face. (Normal adult vision is 20/20.)",
//Week 31 	value 30
"This week, your baby measures over 16 inches long. He weighs about 3 1/3 pounds (about the size of a coconut) and is heading into a growth spurt. He can turn his head from side to side, and his arms, legs, and body are beginning to plump out as needed fat accumulates underneath his skin. He's probably moving a lot, too, so you may have trouble sleeping because your baby's kicks and somersaults keep you up. Take comfort: All this moving is a sign that your baby is active and healthy.",
//Week 32 	value 31  
"By now, your baby weighs 3 3/4 pounds (about the size of a large jicama) and is about 16.7 inches long, taking up a lot of space in your uterus. You're gaining about a pound a week and roughly half of that goes right to your baby. She'll gain a third to half of her birth weight during the next 7 weeks as she fattens up for survival outside the womb. She now has toenails, fingernails, and real hair (or at least respectable peach fuzz). Her skin is becoming soft and smooth as she plumps up in preparation for birth.",
//Week 33 	value 32
"This week your baby weighs a little over 4 pounds and has passed the 17-inch mark (about the size of a pineapple). He's rapidly losing that wrinkled, alien look and his skeleton is hardening. The bones in his skull aren't fused together, which allows them to move and slightly overlap, thus making it easier for him to fit through the birth canal. (The pressure on the head during birth is so intense that many babies are born with a conehead-like appearance.) These bones don't entirely fuse until early adulthood, so they can grow as his brain and other tissue expands during infancy and childhood.",
//Week 34 	value 33
"Your baby now weighs about 4 3/4 pounds (about the size of a cantaloupe) and is almost 18 inches long. Her fat layers — which will help regulate her body temperature once she's born — are filling her out, making her rounder. Her skin is also smoother than ever. Her central nervous system is maturing and her lungs are continuing to mature as well. If you've been nervous about preterm labor, you'll be happy to know that babies born between 34 and 37 weeks who have no other health problems generally do fine. They may need a short stay in the neonatal nursery and may have a few short-term health issues, but in the long run, they usually do as well as full-term babies.",
//Week 35 	value 34
"Your baby doesn't have much room to maneuver now that he's over 18 inches long and tips the scales at 5 1/4 pounds (about the size of a honeydew melon). Because it's so snug in your womb, he isn't likely to be doing somersaults anymore, but the number of times he kicks should remain about the same. His kidneys are fully developed now, and his liver can process some waste products. Most of his basic physical development is now complete — he'll spend the next few weeks putting on weight.",
//Week 36 	value 35
"Your baby is still packing on the pounds — at the rate of about an ounce a day. She now weighs almost 6 pounds and is more than 18 1/2 inches long (about the size of a head of romaine lettuce). She's shedding most of the downy covering of hair that covered her body as well as the vernix caseosa, the waxy substance that covered and protected her skin during her nine-month amniotic bath. Your baby swallows both of these substances, along with other secretions, resulting in a blackish mixture, called meconium, will form the contents of her first bowel movement.  At the end of this week, your baby will be considered 'early term.'' (Full-term is 39 to 40 weeks. Babies born before 37 weeks are pre-term, 41 weeks is late term, and those born after 42 are post-term.) Most likely your baby is already head-down. But if not, your practitioner may suggest scheduling an external cephalic version (ECV). That's a fancy way of saying that your practitioner will apply pressure to your abdomen to try to manipulate your baby into a head-down position.",
//Week 37 	value 36
"Your due date is very close now, but doctors don't consider your baby 'full term' until 39 weeks. Spending the next two weeks in the womb allows your baby's brain and lungs to fully mature. So if you're planning to have a repeat c-section, for example, your practitioner will schedule it for no earlier than 39 weeks unless there's a medical reason to intervene earlier. Many babies have a full head of hair at birth, with locks from 1/2 inch to 1 1/2 inches long. But don't be surprised if your baby's hair isn't the same color as yours. Dark-haired couples are sometimes thrown for a loop when their children come out as blonds or redheads, and fair-haired couples have been surprised by Elvis look-alikes. And then, of course, some babies sport only peach fuzz. At this point your baby weighs 6 1/3 pounds and measures a bit over 19 inches, head to heel (about the size of a bunch of Swiss chard).",
//Week 38 	value 37
"Your baby has really plumped up. She weighs about 6.8 pounds and she is over 19 1/2 inches long (about the size of a leek). She has a firm grasp, which you'll soon be able to test when you hold her hand for the first time! Her organs have matured and are ready for life outside the womb.",
//Week 39 	value 38
"Your baby's full term this week and waiting to greet the world! He continues to build a layer of fat to help control his body temperature after birth, but it's likely he already measures about 20 inches and weighs a bit over 7 pounds, about the size of a mini-watermelon. (Boys tend to be slightly heavier than girls.) The outer layers of his skin are sloughing off as new skin forms underneath.",
//Week 40 	value 39
"It's hard to say for sure how big your baby will be, but the average newborn weighs about 7 1/2 pounds (about the size of a small pumpkin) and is about 20 inches long. His skull bones are not yet fused, which allows them to overlap a bit if it's a snug fit through the birth canal during labor. This so-called 'molding' is the reason your baby's noggin may look a little conehead-ish after birth. Rest assured — it's normal and temporary.",
//Week 41 	value 40
"A bit over 20 inches long, your baby has continued to grow and may now weigh almost 8 pounds. As cozy as he is, your baby can't stay inside you forever. For your baby's safety, your practitioner will talk with you about inducing labor if your baby isn't born in the next week — earlier if there are any problems. Most practitioners won't let you wait more than two weeks past your due date to give birth because it puts you and your baby at increased risk for complications. About 5 to 6 percent of women have prolonged pregnancies that extend three or more weeks beyond their estimated due dates. Babies born at 42 weeks and beyond can have dry parchment-like skin and are often overweight. Waiting that long to deliver also increases your chance of developing an infection in your uterus that could be dangerous for your baby or of having a stillbirth. What's more, your labor is more likely to be prolonged or stalled, both you and your baby have an increased risk of injury during a vaginal delivery, and you double your chances of needing a c-section.",
//Week 42 	value 41
	"Your baby should be born! So go teach him how to catch a ball and how to dance!",
];



/* ::: WEEKS REMAINING ::: */
var today = new Date();
var dueDate=new Date(today.getFullYear(), 5, 2) ;
var one_day=1000*60*60*24;
var days = (Math.ceil((dueDate.getTime()-today.getTime())/(one_day)));
var weeksRemaining = Math.round(days/7);
var todaysWeek = (39-weeksRemaining);
var count = 0;

for (var i = 0; i < todaysWeek; i+=1) {
	count +=1;
}

document.write('<p>' + weeklyFacts[(count)] + '</p>');
console.log(count);



